# Generated by Django 3.0.8 on 2020-08-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
