# Generated by Django 3.0.8 on 2020-08-29 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('county', '0004_auto_20200828_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countylistentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL),
        ),
    ]
